ShjSatDecoder/ShjSatDecoder/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('decoder.urls')),


]

ShjSatDecoder/decoder/urls.py
from django.urls import path
from . import views

app_name = "decoder"

urlpatterns = [
    path('', views.decoder_view, name='decoder_view'),
    path('fetch_and_decode', views.fetch_and_decode, name='fetch_and_decode'),
    path('visualize/', views.visualize_data, name='visualize_data'),
    path('trend-analysis/', views.trend_analysis, name='trend_analysis'),

]

ShjSatDecoder/decoder/models.py
from django.db import models

class ObsHex(models.Model):
    Obs_ID = models.AutoField(primary_key=True)
    Hex_Data = models.TextField()
    Obs_date = models.DateTimeField()

    class Meta:
        indexes = [
            models.Index(fields=['Obs_date']),
        ]

    def __str__(self):
        return f"Obs_ID: {self.Obs_ID}, Date: {self.Obs_date}"

class ObsStatus(models.Model):
    Obs_ID = models.ForeignKey(ObsHex, on_delete=models.CASCADE)
    sensor_status = models.CharField(max_length=13)
    reset_count = models.IntegerField()
    last_reset_cause = models.IntegerField()

    class Meta:
        indexes = [
            models.Index(fields=['reset_count']),
            models.Index(fields=['last_reset_cause']),
        ]

    def __str__(self):
        return f"Obs_ID: {self.Obs_ID.Obs_ID}, Sensor Status: {self.sensor_status}"

ShjSatDecoder/decoder/views.py
import json
import re
import django
from django.shortcuts import render
from django.http import HttpResponse
import datetime
from django.utils import timezone
import pytz
import requests
from urllib.parse import urljoin
from .models import ObsHex, ObsStatus
from django.utils.dateparse import parse_datetime
import time
from django.core.serializers.json import DjangoJSONEncoder
from django.db import connection
from django.db.models import Avg, Count
from django.db.models.functions import TruncDay





# decoder/views.py

def fetch_observation_ids(api_url, norad_id, start_date, end_date):
    formatted_start_date = start_date.strftime('%Y-%m-%d')
    formatted_end_date = end_date.strftime('%Y-%m-%d')
    url = f"{api_url}?id=&status=good&ground_station=&start={formatted_start_date}&end={formatted_end_date}&satellite__norad_cat_id={norad_id}&transmitter_uuid=&transmitter_mode=&transmitter_type=&waterfall_status=&vetted_status=&vetted_user=&observer=&start__lt=&observation_id="
    #print(url)
    try:
        response = requests.get(url, headers = {'User-agent': 'your bot 0.1'})
        response.raise_for_status()  # Raise an error for bad status codes
        data = response.json()
        print("API response (IDs):", data)  # Debug: print the entire response
        return [obs['id'] for obs in data]
    except requests.exceptions.RequestException as e:
        print(f"An error occurred while fetching observation IDs: {e}")
        return []

def fetch_observation_data(api_url, observation_id):
    try:
        observation_url = urljoin(api_url, f"{observation_id}/")
        print(observation_url)
        response = requests.get(observation_url, headers = {'User-agent': 'your bot 0.1'})
        response.raise_for_status()  # Raise an error for bad status codes
        data = response.json()
        return data
    except requests.exceptions.RequestException as e:
        print(f"An error occurred while fetching observation data: {e}")
        return None

def download_data(url):
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an error for bad status codes
        data = response.content
        print("Data from link:")
        print(data)
        print(type(data))
        return data
    except requests.exceptions.RequestException as e:
        print(f"An error occurred while downloading ASCII data: {e}")
        return None

def decode_data_to_hex(data):
    # Convert the decoded data to hex
    hex_data = data.hex().upper()
    print("Data after converting to Hex:")
    print(hex_data)
    # Format the hex data with spaces between each byte
    formatted_hex_data = ' '.join([hex_data[i:i+2] for i in range(0, len(hex_data), 2)])
    return formatted_hex_data

def fetch_and_decode(request):
    if request.method == 'POST':
        api_url = "https://network.satnogs.org/api/observations/"
        norad_id = 55104
        #Getting data starting from the last date in the DB to the current date
        last_obs = ObsHex.objects.order_by('-Obs_date').first()
        if last_obs:
            start_date = last_obs.Obs_date 
            #we can add the below line of code if we want to start from the next day, but I will start from the last observed date just in case
            #+ datetime.timedelta(days=1)
        else:
            start_date = datetime.datetime(2024, 7, 20)

        end_date = timezone.now()

        delay_seconds = 5  # Adjust this value based on the API's rate limit
        current_date = start_date
        results = []

        while current_date <= end_date:
            next_date = current_date + datetime.timedelta(days=1)
            observation_ids = fetch_observation_ids(api_url, norad_id, current_date, next_date)
            current_date += datetime.timedelta(days=1)
            if observation_ids:
                for obs_id in observation_ids:
                    time.sleep(delay_seconds)
                    observation = fetch_observation_data(api_url, obs_id)
                    if observation and "demoddata" in observation and len(observation["demoddata"]) > 0:
                        ascii_file_url = observation["demoddata"][0]["payload_demod"]
                        ascii_data = download_data(ascii_file_url)
                        if ascii_data:
                            hex_data = decode_data_to_hex(ascii_data)
                            expected_start = "82 6C 64 AA 9E A6 E0 82 6C 60 AA 9E A6 61 03 F0 45 53 45 52 50 F6 00 00 00 00"
                            expected_end = "00"
                            hex_words = hex_data.split()
                            
                            if len(hex_words) == 272 and hex_data.startswith(expected_start) and hex_data.endswith(expected_end):
                                results.append({
                                    'observation_id': obs_id,
                                    'hex_data': hex_data,
                                    'download_link': ascii_file_url
                                })
                                # Check if the observation already exists
                                if ObsHex.objects.filter(Obs_ID=obs_id).exists():
                                    print(f"Observation ID {obs_id} already exists in the database.")
                                    continue

                                # Save hex data to the database
                                observation_date = parse_datetime(observation["start"])
                                obs_hex = ObsHex(Obs_ID=obs_id, Hex_Data=hex_data, Obs_date=observation_date)
                                obs_hex.save()

                                # Decode hex data and save to obs_status table
                                decoded_values = hex_to_decimal(hex_data)
                                if decoded_values:
                                    decoded_values.pop(1)
                                    sensor_status = decoded_values[0]
                                    reset_count = int(decoded_values[1].split(": ")[1])
                                    last_reset_cause = int(decoded_values[2].split(": ")[1])

                                    obs_status = ObsStatus(
                                        Obs_ID=obs_hex,
                                        sensor_status=sensor_status,
                                        reset_count=reset_count,
                                        last_reset_cause=last_reset_cause
                                    )
                                    obs_status.save()
                                
                            else:
                                error_message = f"Hex data for observation_id {obs_id} does not meet the required criteria: "
                                if len(hex_words) != 272:
                                    error_message += "Incorrect number of words. "
                                if not hex_data.startswith(expected_start):
                                    error_message += "Does not start with the expected sequence. "
                                if not hex_data.endswith(expected_end):
                                    error_message += "Does not end with the expected sequence."
                                results.append({
                                    'observation_id': obs_id,
                                    'error': error_message
                                })
                        else:
                            results.append({'observation_id': obs_id, 'error': 'Failed to download data'})
                        # Adding delay between requests to avoid hitting the API rate limit
                        time.sleep(delay_seconds)
            else:
                results.append({'error': f'No observations found between {current_date} and {next_date}'})
                time.sleep(delay_seconds)
            
        return render(request, 'fetch_decode_results.html', {'results': results})

    return render(request, 'decoder/decoder.html')



# Create your views here.
def hex_to_decimal(hex_str):
    try:
        hex_values = hex_str.split()
        decimal_values = [int(h, 16) for h in hex_values]
        little_endian_values = []
        status_list = []  # To store the 13-bit status strings

        idx = 0
        while idx < len(decimal_values):
            if idx == 26:  # Word number 27 and 28 combined (13-bit binary representation)
                combined_value = ((decimal_values[idx + 1] << 8) | decimal_values[idx]) & 0x1FFF  # Mask to keep only 13 bits
                bin_value = bin(combined_value)[2:].zfill(13)  # Convert to binary and zero-fill to 13 bits
                little_endian_values.append(bin_value)
                # Create status labels for the 13 bits
                status_labels = [
                    "Operation Mode", "Antenna Status", "Beacon", "RTC", "IF Board",
                    "CAM 5mp", "CAM 2mp", "iXRD", "S-Band Transmitter", "UHV/VHF Modem",
                    "ADCS", "EPS", "Battery"
                ]
                
                # Generate status strings
                for i in range(12, -1, -1):  # Iterate over the 13 bits
                    bit_status = (combined_value >> i) & 1
                    status_list.append(f"{status_labels[12 - i]}: {'ok' if bit_status == 1 else 'error'}")

                little_endian_values.append(status_list)
                idx += 2
            elif idx == 28:  # Word number 29 and 30 combined (u2)
                u2_value = (decimal_values[idx + 1] << 8) | decimal_values[idx]
                little_endian_values.append(f"Reset count: {u2_value}")
                idx += 2
            elif idx == 30:  # Word number 31 (u1)
                little_endian_values.append(f"Last reset cause: {decimal_values[idx]}")
                idx += 1
            else:
                # Convert to little-endian formats

ShjSatDecoder/decoder/templates/decoder.html
{% extends 'test.html' %}
{% load static %}
{% block content %}
<!-- 

<h1>Hex Decoder</h1>
    {% if error_message %}
        <p class="error-message">{{ error_message }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <label for="hex_input">Enter 272 Hex Words (separated by spaces):</label>
        <input type="text" id="hex_input" name="hex_input" value="{{ hex_input|default:'' }}" pattern="(?:[0-9a-fA-F]{2}\s){271}[0-9a-fA-F]{2}">
        <button type="submit">Decode</button>
    </form>
    {% if decoded_values %}
        <h2>Decoded Values (Little Endian):</h2>
        <ul>
            {% for value in decoded_values %}
                <li>{{ value }}</li>
            {% endfor %}
        </ul>
    {% endif %}
-->

<div class="max-w-3xl mx-auto mt-10 p-6 bg-gray-800 rounded-lg shadow-md">
    <!-- Dark Mode Toggle Button -->
    <div class="flex justify-end">
        <button id="theme-toggle" class="bg-blue-500 text-white px-4 py-2 rounded-md mb-4">
            Toggle Dark Mode
        </button>
    </div>

    <h1 class="text-2xl font-semibold mb-6">Hex Decoder</h1>

    <form method="post">
        {% csrf_token %}
        <label for="hex-input" class="block mb-2 text-sm font-medium">Enter 272 Hex Words (separated by spaces):</label>
        <input type="text" id="hex_input" name="hex_input" value="{{ hex_input|default:'' }}" pattern="(?:[0-9a-fA-F]{2}\s){271}[0-9a-fA-F]{2}" rows="10" class="w-full p-4 border border-gray-700 rounded-md text-gray-900 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" required></textarea>
        <button type="submit" class="mt-4 w-full bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 transition duration-200">Decode</button>
    </form>

    <form method="post" action="{% url 'decoder:visualize_data' %}">
        {% csrf_token %}
        <button type="submit" class="mt-4 w-full bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 transition duration-200">See data graphs</button>
    </form>

    {% if error_message %}
        <div class="bg-red-500 text-white p-4 rounded-md mb-6">
            {{ error_message }}
        </div>
    {% endif %}

    {% if status_list %}
        <div class="mt-6">
            <h2 class="text-xl font-semibold mb-4">Sensor Status:</h2>
            <ul class="space-y-2">
                {% for status in status_list %}
                    <li class="bg-gray-700 p-3 rounded-md {% if 'ok' in status %}text-green-500{% else %}text-red-500{% endif %}">
                        {{ status }}
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    {% if decoded_values %}
        <div class="mt-6">
            <h2 class="text-xl font-semibold mb-4">Decoded Values:</h2>
            <ul class="space-y-2">
                {% for value in decoded_values %}
                    <li class="bg-gray-700 p-3 rounded-md">{{ value }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
</div>
{% endblock %}

ShjSatDecoder/decoder/templates/fetch_decode_results.html
<!-- decoder/templates/decoder/fetch_decode_results.html -->
{% extends "test.html" %}

{% block content %}
<div class="max-w-3xl mx-auto mt-10 p-6 bg-gray-800 rounded-lg shadow-md">
    <!-- Dark Mode Toggle Button -->
    <div class="flex justify-end">
        <button id="theme-toggle" class="bg-blue-500 text-white px-4 py-2 rounded-md mb-4">
            Toggle Dark Mode
        </button>
    </div>

    <h1 class="text-2xl font-semibold mb-6">Fetch and Decode Results</h1>

    <ul class="space-y-2">
        {% for result in results %}
            <li class="bg-gray-700 p-3 rounded-md">
                {% if result.error %}
                    <p>{{ result.error }}</p>
                {% else %}
                    <p><strong>Observation ID:</strong> {{ result.observation_id }}</p>
                    <p><strong>Hex Data:</strong> {{ result.hex_data }}</p>
                    <p><strong>Download Link:</strong> <a href="{{ result.download_link }}" class="text-blue-400 underline" target="_blank">{{ result.download_link }}</a></p>
                {% endif %}
            </li>
        {% endfor %}
    </ul>

    <div class="mt-4">
        <a href="{% url 'decoder:decoder_view' %}" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 transition duration-200">Back</a>
    </div>
</div>
{% endblock %}

ShjSatDecoder/decoder/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SAASST Sharjah Decoder</title>
    {% load static %}
    <!-- Tailwind CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://code.jquery.com/jquery-3.7.1.slim.js" integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc=" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>

</head>
<body class="bg-gray-900 text-white" id="theme">
    <div class="container mx-auto p-4">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

ShjSatDecoder/decoder/templates/trend_analysis.html
{% extends 'test.html' %}
{% load static %}
{% block content %}

<h2 class="text-2xl font-semibold text-gray-800 mb-4">Daily Trends</h2>

<!-- Add navigation button -->
<div class="mt-4">
    <a href="{% url 'visualize_data' %}" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 transition duration-200">Back to Data Visualization</a>
</div>

<table class="min-w-full bg-white shadow-md rounded-md overflow-hidden">
    <thead class="bg-blue-500 text-white">
        <tr>
            <th class="px-4 py-2 text-left">Date</th>
            <th class="px-4 py-2 text-left">Average Reset Count</th>
            <th class="px-4 py-2 text-left">Total Observations</th>
        </tr>
    </thead>
    <tbody class="text-gray-700">
        {% for trend in trends %}
        <tr class="hover:bg-gray-100">
            <td class="px-4 py-2">{{ trend.date }}</td>
            <td class="px-4 py-2">{{ trend.avg_reset_count }}</td>
            <td class="px-4 py-2">{{ trend.reset_count_count }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

ShjSatDecoder/decoder/templates/visualize_data.html
{% extends 'test.html' %}
{% load static %}
{% block content %}

<form method="get" class="space-x-4 flex items-center p-4 bg-gray-50 rounded-md shadow-md">
    <label for="sort" class="font-semibold text-gray-700">Sort by:</label>
    <select name="sort" id="sort" class="bg-white border border-gray-300 text-gray-700 p-2 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500">
        <option value="Obs_ID_id">Observation ID</option>
        <option value="reset_count">Reset Count</option>
        <option value="last_reset_cause">Last Reset Cause</option>
    </select>

    <select name="direction" class="bg-white border border-gray-300 text-gray-700 p-2 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500">
        <option value="asc">Ascending</option>
        <option value="desc">Descending</option>
    </select>

    <label for="start_date" class="font-semibold text-gray-700">Start Date:</label>
    <input type="date" name="start_date" id="start_date" class="bg-white border border-gray-300 text-gray-700 p-2 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500">

    <label for="end_date" class="font-semibold text-gray-700">End Date:</label>
    <input type="date" name="end_date" id="end_date" class="bg-white border border-gray-300 text-gray-700 p-2 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500">

    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-md shadow-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500">Filter</button>
</form>


<div class="container mt-5">

    <form method="post" action="{% url 'decoder:fetch_and_decode' %}">
        {% csrf_token %}
        <button type="submit" class="mt-4 w-full bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 transition duration-200" onclick="showLoading()">Fetch up to date data</button>
    </form>

    <div id="loading" style="display:none;">
        <div class="spinner"></div>
        <p id="loading-text">This might take a while depending on how many observations there are</p>
    </div>
    
    <h2>Data Visualization</h2>

    <div class="row mt-4">
        <div class="col-md-6">
            <h4>Reset Counts</h4>
            <canvas id="resetCountsChart"></canvas>
        </div>
        <div class="col-md-6">
            <h4>Last Reset Causes</h4>
            <canvas id="lastResetCausesChart"></canvas>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12">
            <h4 class="text-lg font-semibold mb-4">Sensor Status Summary</h4>
            <canvas id="sensorStatusSummaryChart"></canvas>
        </div>
    </div>
    
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="bg-gray-800 shadow-md rounded-lg">
                <div class="bg-blue-600 text-white p-4 rounded-t-lg">
                    <h5 class="text-lg font-semibold">Explanation of Sensor Bits</h5>
                </div>
                <div class="p-4">
                    <div class="mb-4">
                        <p class="text-sm text-gray-300"><strong>Key:</strong> <span class="text-green-500">1 = Working</span>, <span class="text-red-500">0 = Error</span></p>
                    </div>
                    <div class="grid grid-cols-1 gap-4">
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 0:</span>
                            <p>Battery - Indicates if the battery is functioning correctly.</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 1:</span>
                            <p>EPS - Represents the Electrical Power System's operational status.</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 2:</span>
                            <p>ADCS - Indicates the Attitude Determination and Control System's status.</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 3:</span>
                            <p>U/V Modem - Shows the status of the UHF/VHF modem.</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 4:</span>
                            <p>SBand - Indicates the status of the S-band transmitter.</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 5:</span>
                            <p>iXRD - Represents the X-ray detector's operational status.</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 6:</span>
                            <p>CAM2MP - Indicates the functionality of the 2MP camera.</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 7:</span>
                            <p>CAM5MP - Indicates the functionality of the 5MP camera.</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 8:</span>
                            <p>IF Board - Represents the status of the Interface Board.</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 9:</span>
                            <p>RTC - Indicates the status of the Real-Time Clock module.</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 10:</span>
                            <p>Beacon - Shows whether the beacon is operational.</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 11:</span>
                            <p>Antennas - Indicates antenna deployment status (<span class="text-green-500">1 = All Deployed</span>, <span class="text-red-500">0 = Non-Deployed</span>).</p>
                        </div>
                        <div class="flex items-start">
                            <span class="font-bold text-blue-500 mr-2">Bit 12:</span>
                            <p>Op Mode - Reflects the operational mode of the system:
                                <ul class="list-disc pl-5 text-gray-300 mt-1">
                                    <li>0: Startup</li>
                                    <li>1: Nominal</li>
                                    <li>2: Safe</li>
                                    <li>3: ADCS Calibration</li>
                                    <li>4: Recovery</li>
                                    <li>5: Sun Pointing</li>
                                    <li>6: Camera Operation</li>
                                    <li>7: XRD Operation</li>
                                    <li>8: Diagnostics</li>
                                </ul>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    
    
<!-- 
    <div class="row mt-4">
        <div class="col-md-12">
            <h4>Debug Data</h4>
            <pre>{{ reset_dates }}</pre>
            <pre>{{ reset_counts }}</pre>
        </div>
    </div>
-->
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Reset Counts Chart
        var resetCountsCtx = document.getElementById('resetCountsChart').getContext('2d');
        var resetCountsData = JSON.parse('{{ reset_counts|escapejs }}');
        var resetDatesData = JSON.parse('{{ reset_dates|escapejs }}');
        var resetCountsChart = new Chart(resetCountsCtx, {
            type: 'bar',
            data: {
                labels: resetDatesData,
                datasets: [{
                    label: 'Reset Counts',
                    data: resetCountsData,
                    backgroundColor: 'rgba(75, 192, 192, 0.2)',
                    borderColor: 'rgba(75, 192, 192, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });

        // Last Reset Causes Chart
        var lastResetCausesCtx = document.getElementById('lastResetCausesChart').getContext('2d');
        var lastResetCausesData = JSON.parse('{{ last_reset_causes|escapejs }}');
        var resetDatesData = JSON.parse('{{ reset_dates|escapejs }}');
        var lastResetCausesChart = new Chart(lastResetCausesCtx, {
            type: 'bar',
            data: {
                labels: resetDatesData,
                datasets: [{
                    label: 'Last Reset Causes',
                    data: lastResetCausesData,
                    backgroundColor: 'rgba(153, 102, 255, 0.2)',
                    borderColor: 'rgba(153, 102, 255, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });

        // Sensor Status Summary Chart
        var sensorStatusSummaryCtx = document.getElementById('sensorStatusSummaryChart').getContext('2d');
        var sensorStatusSummaryLabels = JSON.parse('{{ sensor_status_summary_labels|escapejs }}');
        var sensorStatusSummaryValues = JSON.parse('{{ sensor_status_summary_values|escapejs }}');
        var sensorStatusSummaryChart = new Chart(sensorStatusSummaryCtx, {
            type: 'pie',
            data: {
                labels: sensorStatusSummaryLabels,
                datasets: [{
                    label: 'Sensor Status Summary',
                    data: sensorStatusSummaryValues,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: 'Sensor Status Summary'
                    }
                }
            }
        });
    });
</script>


{% endblock %}